import type { NotificationItem } from '@/shared/notifications/types'

/**
 * Shared by the header bell badge (shell) and the Notifications & Alerts
 * screen (dashboard module) so both read the same list instead of two
 * separate mock sources drifting apart.
 */
export const notificationsMock: NotificationItem[] = [
  {
    id: 'ntf_001',
    category: 'approval',
    title: 'Leave request awaiting your approval',
    description: 'Arjun Mehta requested 3 days of annual leave (Sep 15–17).',
    timestamp: '2026-09-08T13:40:00Z',
    read: false,
    href: '/my-work/approvals/apr_5521',
  },
  {
    id: 'ntf_002',
    category: 'ticket',
    title: 'SLA breach on IT-4021',
    description: '"VPN access request" has exceeded its SLA by 2h 10m.',
    timestamp: '2026-09-08T12:05:00Z',
    read: false,
    href: '/service-desk/tickets/IT-4021',
  },
  {
    id: 'ntf_003',
    category: 'task',
    title: 'Task overdue: Q3 budget review',
    description: 'This task was due Sep 5 and is now 3 days overdue.',
    timestamp: '2026-09-08T09:15:00Z',
    read: false,
    href: '/my-work/tasks/tsk_8842',
  },
  {
    id: 'ntf_004',
    category: 'leave',
    title: 'Your leave request was approved',
    description: 'Sarah Chen approved your annual leave for Sep 22–24.',
    timestamp: '2026-09-07T17:30:00Z',
    read: true,
    href: '/hrms/leave/lv_3391',
  },
  {
    id: 'ntf_005',
    category: 'ticket',
    title: 'New reply on HR-1188',
    description: 'HR Desk replied to "Payroll discrepancy for August".',
    timestamp: '2026-09-07T15:02:00Z',
    read: true,
    href: '/service-desk/tickets/HR-1188',
  },
  {
    id: 'ntf_006',
    category: 'system',
    title: 'Scheduled maintenance tonight',
    description: 'OctoSphere will be unavailable 11:00 PM–12:00 AM IST.',
    timestamp: '2026-09-07T10:00:00Z',
    read: true,
    href: '/administration/system-monitoring',
  },
  {
    id: 'ntf_007',
    category: 'approval',
    title: 'Expense report approved',
    description: 'Your Sep 1–5 travel expense report was approved.',
    timestamp: '2026-09-06T14:20:00Z',
    read: true,
    href: '/my-work/approvals/apr_5498',
  },
  {
    id: 'ntf_008',
    category: 'task',
    title: 'You were assigned a new task',
    description: 'Sarah Chen assigned you "Prepare onboarding checklist".',
    timestamp: '2026-09-06T11:45:00Z',
    read: true,
    href: '/my-work/tasks/tsk_8801',
  },
  {
    id: 'ntf_009',
    category: 'ticket',
    title: 'Ticket resolved: AD-3390',
    description: '"New laptop request" was marked resolved by IT Desk.',
    timestamp: '2026-09-05T16:10:00Z',
    read: true,
    href: '/service-desk/tickets/AD-3390',
  },
  {
    id: 'ntf_010',
    category: 'leave',
    title: 'Leave balance updated',
    description: 'Your annual leave balance was credited for September.',
    timestamp: '2026-09-01T08:00:00Z',
    read: true,
    href: '/hrms/leave/balance',
  },
  {
    id: 'ntf_011',
    category: 'system',
    title: 'New policy published',
    description: 'The updated Remote Work Policy is now available.',
    timestamp: '2026-08-30T09:00:00Z',
    read: true,
    href: '/hrms/documents/policies/pol_112',
  },
  {
    id: 'ntf_012',
    category: 'approval',
    title: 'Timesheet approval pending',
    description: '4 team timesheets are waiting on your review.',
    timestamp: '2026-08-29T18:00:00Z',
    read: true,
    href: '/my-work/approvals/apr_5310',
  },
]
